version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: medease_postgres
    environment:
      POSTGRES_DB: medease_db
      POSTGRES_USER: medease_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medease_user -d medease_db"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
